/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import deepspace.DamageToUI;
import deepspace.EnemyToUI;
import deepspace.LootToUI;

/**
 *
 * @author JuanAntonio
 */
public class EnemyView extends javax.swing.JPanel {
    
    private LootView loot;
    private DamageView damage;
    /**
     * Creates new form EnemyView
     */
    public EnemyView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        ammoPowerText = new javax.swing.JLabel();
        ammoPower = new javax.swing.JLabel();
        shieldPowerText = new javax.swing.JLabel();
        shieldPower = new javax.swing.JLabel();
        lootPanel = new javax.swing.JPanel();
        damagePanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enemigo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jLabel1.setText("Nombre:");

        name.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        name.setText("jLabel2");

        ammoPowerText.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        ammoPowerText.setText("Potencia de Fuego");

        ammoPower.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        ammoPower.setText("jLabel4");

        shieldPowerText.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        shieldPowerText.setText("Potencia de Protección");

        shieldPower.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        shieldPower.setText("jLabel6");

        lootPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lootPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(shieldPowerText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(shieldPower))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ammoPowerText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ammoPower))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(name)))
                        .addGap(0, 155, Short.MAX_VALUE))
                    .addComponent(damagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ammoPowerText)
                    .addComponent(ammoPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shieldPowerText)
                    .addComponent(shieldPower))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lootPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(damagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void setEnemyStarShip(EnemyToUI enemy){
        LootView lootView=new LootView();
        DamageView damageView=new DamageView();
        
        name.setText(enemy.getName());
        ammoPower.setText(Float.toString(enemy.getAmmoPower()));
        shieldPower.setText(Float.toString(enemy.getShieldPower()));
        LootToUI loot=enemy.getLoot();
        lootView.setLoot(loot);
        DamageToUI damage=enemy.getDamage();
        damageView.setDamage(damage);
        
        lootPanel.removeAll();
        lootPanel.add(lootView);
        damagePanel.removeAll();
        damagePanel.add(damageView);
        repaint();
        revalidate();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ammoPower;
    private javax.swing.JLabel ammoPowerText;
    private javax.swing.JPanel damagePanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel lootPanel;
    private javax.swing.JLabel name;
    private javax.swing.JLabel shieldPower;
    private javax.swing.JLabel shieldPowerText;
    // End of variables declaration//GEN-END:variables
}
