/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import deepspace.LootToUI;
/**
 *
 * @author pedro
 */
public class LootView extends javax.swing.JPanel {

    /**
     * Creates new form LootView
     */
    public LootView() {
        initComponents();
    }
    
    void setLoot(LootToUI loot){
        Armas.setText(Integer.toString(loot.getnWeapons()));
        Combustible.setText(Integer.toString(loot.getnSupplies()));
        Escudos.setText(Integer.toString(loot.getnShields()));
        Hangar.setText(Integer.toString(loot.getnHangars()));
        Medallas.setText(Integer.toString(loot.getnMedals()));
        repaint();
        revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Armas = new javax.swing.JLabel();
        Escudos = new javax.swing.JLabel();
        Hangar = new javax.swing.JLabel();
        Combustible = new javax.swing.JLabel();
        Medallas = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botín", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 11))); // NOI18N

        jLabel2.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jLabel2.setText("Armas:");

        jLabel3.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jLabel3.setText("Escudos:");

        jLabel4.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jLabel4.setText("Hangar:");

        jLabel5.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jLabel5.setText("Combustible");

        jLabel6.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        jLabel6.setText("Medallas:");

        Armas.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        Armas.setText("jLabel7");

        Escudos.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        Escudos.setText("jLabel8");

        Hangar.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        Hangar.setText("jLabel9");

        Combustible.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        Combustible.setText("jLabel10");

        Medallas.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        Medallas.setText("jLabel11");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Escudos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Hangar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Medallas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Armas)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Combustible)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Armas)
                        .addComponent(jLabel5)
                        .addComponent(Combustible)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Escudos))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Hangar)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(Medallas))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Armas;
    private javax.swing.JLabel Combustible;
    private javax.swing.JLabel Escudos;
    private javax.swing.JLabel Hangar;
    private javax.swing.JLabel Medallas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
