/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import View.View;
import controller.ControllerGraph;
import deepspace.DamageToUI;
import deepspace.EnemyToUI;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import deepspace.GameState;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;
import deepspace.HangarToUI;
import deepspace.LootToUI;
import deepspace.NumericDamageToUI;
import deepspace.SpaceStationToUI;
import deepspace.SpecificDamageToUI;
import java.awt.Component;

/**
 *
 * @author JuanAntonio
 */
public class MainWindow extends JFrame implements View{
    static ControllerGraph controller;
    private String name = "DeepSpace";
    private SpaceStationView stationView;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        setTitle(name);
        stationView=new SpaceStationView();
        panelPruebas.add(stationView);
        repaint();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                controller.finish(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPruebas = new javax.swing.JPanel();
        seleccionados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionados.setText("SELECCION");
        seleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPruebas, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionados)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPruebas, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seleccionados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionadosActionPerformed
        for(Component c:panelPruebas.getComponents()){
            System.out.println("Haciendo algo");
        }

    }//GEN-LAST:event_seleccionadosActionPerformed

    @Override
    public void setController(ControllerGraph unControlador) {
        controller=unControlador;
    }

    @Override
    public void updateView() {
        panelPruebas.removeAll();
        /*ShieldToUI sbprueba=controller.dameUnEscudoPrueba();
        ShieldBoosterView vistaEscudoPrueba=new ShieldBoosterView();
        vistaEscudoPrueba.setShieldBooster(sbprueba);
        panelPruebas.add(vistaEscudoPrueba);*/
        /*WeaponToUI wprueba=controller.dameUnArmaPrueba();
        WeaponView vistaArmaPrueba=new WeaponView();
        vistaArmaPrueba.setWeapon(wprueba);
        panelPruebas.add(vistaArmaPrueba);*/
        /*HangarToUI hprueba=controller.dameUnHangarPrueba();
        HangarView vistaHangarPrueba=new HangarView();
        vistaHangarPrueba.setHangar(hprueba);
        panelPruebas.add(vistaHangarPrueba);*/
        /*DamageToUI nd=controller.dameUnNumericDamagePrueba();
        DamageView dv=new DamageView();
        dv.setDamage(nd);
        panelPruebas.add(dv);*/
        EnemyToUI enemy=controller.dameUnEnemyStarShipPrueba();
        EnemyStarShipView Enemy=new EnemyStarShipView();
        Enemy.setEnemyStarShip(enemy);
        panelPruebas.add(Enemy);
        
       /*SpaceStationToUI station=controller.dameUnSpaceStationPrueba();
        SpaceStationView Station=new SpaceStationView();
        Station.setSpaceStation(station);
        panelPruebas.add(Station);*/
        
        /*LootToUI loot=controller.dameUnLootPrueba();
        LootView Loot=new LootView();
        Loot.setLoot(loot);
        panelPruebas.add(Loot);*/
        
        repaint();
        revalidate();
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public String getAppName() {
        return name;
    }

    @Override
    public ArrayList<String> getNames() {
        NamesCapture namesCapture = new NamesCapture (this);
        return namesCapture.getNames();
    }

    @Override
    public boolean confirmExitMessage() {
        return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?", getAppName(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPruebas;
    private javax.swing.JButton seleccionados;
    // End of variables declaration//GEN-END:variables
}
