/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import View.View;
import controller.ControllerGraph;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import deepspace.GameState;
import deepspace.WeaponToUI;
import deepspace.ShieldToUI;

/**
 *
 * @author JuanAntonio
 */
public class MainWindow extends JFrame implements View{
    static ControllerGraph controller;
    private String name = "DeepSpace";
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        
        setTitle(name);
        
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                controller.finish(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPruebas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPruebas, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPruebas, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setController(ControllerGraph unControlador) {
        controller=unControlador;
    }

    @Override
    public void updateView() {
        /*ShieldToUI sbprueba=controller.dameUnEscudoPrueba();
        ShieldBoosterView vistaEscudoPrueba=new ShieldBoosterView();
        vistaEscudoPrueba.setShieldBooster(sbprueba);
        panelPruebas.add(vistaEscudoPrueba);*/
        WeaponToUI wprueba=controller.dameUnArmaPrueba();
        WeaponView vistaArmaPrueba=new WeaponView();
        vistaArmaPrueba.setWeapon(wprueba);
        panelPruebas.add(vistaArmaPrueba);
        
        repaint();
        revalidate();
    }

    @Override
    public void showView() {
        setVisible(true);
    }

    @Override
    public String getAppName() {
        return name;
    }

    @Override
    public ArrayList<String> getNames() {
        NamesCapture namesCapture = new NamesCapture (this);
        return namesCapture.getNames();
    }

    @Override
    public boolean confirmExitMessage() {
        return (JOptionPane.showConfirmDialog(this, "¿Estás segur@ que deseas salir?", getAppName(), JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelPruebas;
    // End of variables declaration//GEN-END:variables
}
