/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import deepspace.NumericDamageToUI;

/**
 *
 * @author JuanAntonio
 */
public class NumericDamageView extends DamageView {

    /**
     * Creates new form NumericDamageView
     */
    public NumericDamageView() {
        initComponents();
    }
    
    public void setNumericDamage(NumericDamageToUI d){
        nWeapons.setText(Integer.toString(d.getNWeapons()));
        nShields.setText(Integer.toString(d.getNShields()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nShieldsText = new javax.swing.JLabel();
        nWeaponsText = new javax.swing.JLabel();
        nShields = new javax.swing.JLabel();
        nWeapons = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N
        setPreferredSize(new java.awt.Dimension(189, 116));

        nShieldsText.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        nShieldsText.setText("Número de escudos: ");

        nWeaponsText.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        nWeaponsText.setText("Número de armas:");

        nShields.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        nShields.setText("jLabel1");

        nWeapons.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        nWeapons.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nWeaponsText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nWeapons))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nShieldsText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nShields)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nShieldsText)
                    .addComponent(nShields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nWeaponsText)
                    .addComponent(nWeapons))
                .addGap(0, 32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nShields;
    private javax.swing.JLabel nShieldsText;
    private javax.swing.JLabel nWeapons;
    private javax.swing.JLabel nWeaponsText;
    // End of variables declaration//GEN-END:variables
}
