/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import deepspace.ShieldToUI;

/**
 *
 * @author JuanAntonio
 */
public class ShieldBoosterView extends CombatElementView {

    private boolean selected=false;
    
    public ShieldBoosterView() {
        setOpaque(selected);
        initComponents();
    }
    
    @Override    
    public boolean isSelected(){
        return selected;
    }
    
    @Override
    public boolean isWeapon(){
        return false;
    }
    
    void setShieldBooster(ShieldToUI sb){
        uses.setText(Integer.toString(sb.getUses()));
        boost.setText(Float.toString(sb.getBoost()));
        repaint();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        usesText = new javax.swing.JLabel();
        boostText = new javax.swing.JLabel();
        uses = new javax.swing.JLabel();
        boost = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setPreferredSize(new java.awt.Dimension(124, 92));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("AR DESTINE", 0, 14)); // NOI18N
        name.setText("ESCUDO");

        usesText.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        usesText.setText("Usos:");

        boostText.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        boostText.setText("Potencia:");

        uses.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        uses.setText("jLabel1");

        boost.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        boost.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boostText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(boost))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usesText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(uses))))
                    .addComponent(name))
                .addGap(0, 11, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usesText)
                    .addComponent(uses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boostText)
                    .addComponent(boost))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel boost;
    private javax.swing.JLabel boostText;
    private javax.swing.JLabel name;
    private javax.swing.JLabel uses;
    private javax.swing.JLabel usesText;
    // End of variables declaration//GEN-END:variables
}
