/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import deepspace.ShieldToUI;
import deepspace.SpaceStationToUI;
import deepspace.WeaponToUI;
import java.util.ArrayList;
/**
 *
 * @author pedro
 */
public class SpaceStationView extends javax.swing.JPanel {
    private HangarView hangarView;
    /**
     * Creates new form SpaceStationView
     */
    public SpaceStationView() {
        initComponents();
        
        hangarView=new HangarView();
        Hangar.add(hangarView);
        repaint();
    }

    void setSpaceStation(SpaceStationToUI station){
        HangarView h=new HangarView();
        Ataque.setText(Float.toString(station.getAmmoPower()));
        Defensa.setText(Float.toString(station.getShieldPower()));
        Combustible.setText(Float.toString(station.getFuelUnits()));
        Medallas.setText(Integer.toString(station.getnMedals()));
        
        Armas.removeAll();
        Escudos.removeAll();
        if(station.getHangar()!=null){
            h.setHangar(station.getHangar());
            Hangar.add(h);
        }
        else{
            Hangar.setVisible(false);
        }
        
        
        ArrayList<WeaponToUI>weapons=station.getWeapons();
        ArrayList<ShieldToUI>shields=station.getShieldBoosters();
        ShieldBoosterView sbv;
        for (ShieldToUI sb:shields){
            sbv=new ShieldBoosterView();
            sbv.setShieldBooster(sb);
            Escudos.add(sbv);
        }
        WeaponView wv;
        for (WeaponToUI w:weapons){
            wv=new WeaponView();
            wv.setWeapon(w);
            Armas.add(wv);
        }
        DamageView dv=new DamageView();
        if(station.getPendingDamage()!=null){
            dv.setDamage(station.getPendingDamage());
            Damage.add(dv);
        }
        else{
            Damage.setVisible(false);
        }
        
        
        repaint();
        revalidate();
        
    }
    
    ArrayList<Integer> getSelectedWeapons(){
        return hangarView.getSelectedWeapons();
    }
    
    ArrayList<Integer> getSelectedShields(){
        return hangarView.getSelectedShields();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Ataque = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Defensa = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Combustible = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Medallas = new javax.swing.JLabel();
        Armas = new javax.swing.JPanel();
        Escudos = new javax.swing.JPanel();
        Hangar = new javax.swing.JPanel();
        Damage = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estación espacial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la estación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N

        jLabel2.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        jLabel2.setText("Potencia de Ataque: ");

        Ataque.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        Ataque.setText("jLabel3");

        jLabel3.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        jLabel3.setText("Potencia de Defensa:");

        Defensa.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        Defensa.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        jLabel5.setText("Nivel de Combustible: ");

        Combustible.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        Combustible.setText("jLabel6");

        jLabel6.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        jLabel6.setText("Medallas: ");

        Medallas.setFont(new java.awt.Font("AR DESTINE", 0, 10)); // NOI18N
        Medallas.setText("jLabel7");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Defensa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Ataque)
                        .addGap(0, 17, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(4, 4, 4)
                        .addComponent(Medallas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel5)
                        .addGap(5, 5, 5)
                        .addComponent(Combustible)))
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Ataque)
                    .addComponent(jLabel5)
                    .addComponent(Combustible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(Medallas)
                    .addComponent(Defensa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Armas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Armas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N

        Escudos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Escudos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N

        Hangar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hangar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 12))); // NOI18N

        javax.swing.GroupLayout HangarLayout = new javax.swing.GroupLayout(Hangar);
        Hangar.setLayout(HangarLayout);
        HangarLayout.setHorizontalGroup(
            HangarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        HangarLayout.setVerticalGroup(
            HangarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 56, Short.MAX_VALUE)
        );

        Damage.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daño pendiente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 11))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Damage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Escudos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Armas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(Hangar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(Armas, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(Escudos, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(Hangar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Damage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Armas;
    private javax.swing.JLabel Ataque;
    private javax.swing.JLabel Combustible;
    private javax.swing.JPanel Damage;
    private javax.swing.JLabel Defensa;
    private javax.swing.JPanel Escudos;
    private javax.swing.JPanel Hangar;
    private javax.swing.JLabel Medallas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
