/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import deepspace.SpecificDamageToUI;
import deepspace.WeaponType;

/**
 *
 * @author JuanAntonio
 */
public class SpecificDamageView extends DamageView {

    /**
     * Creates new form SpecificDamageView
     */
    public SpecificDamageView() {
        initComponents();
    }
    
    public void setSpecificDamage(SpecificDamageToUI d){
        nShields.setText(Integer.toString(d.getNShields()));
        javax.swing.JLabel aux;
        String cad="";
        for(WeaponType wt:d.getWeapons()){
            if(wt==WeaponType.LASER)
                cad+="LASER  ";
            else{
                if(wt==WeaponType.MISSILE)
                    cad+="MISSILE  ";
                else{
                    cad+="PLASMA  ";
                }
            }
            tipos.setText(cad);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nShieldsText = new javax.swing.JLabel();
        nShields = new javax.swing.JLabel();
        weaponsText = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        weapons = new javax.swing.JPanel();
        tipos = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Daño", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("AR DESTINE", 0, 11))); // NOI18N

        nShieldsText.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        nShieldsText.setText("Número de escudos:");

        nShields.setFont(new java.awt.Font("AR DESTINE", 0, 12)); // NOI18N
        nShields.setText("jLabel1");

        weaponsText.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        weaponsText.setText("Tipos de armas:");

        tipos.setFont(new java.awt.Font("AR DESTINE", 0, 11)); // NOI18N
        tipos.setText("jLabel1");

        javax.swing.GroupLayout weaponsLayout = new javax.swing.GroupLayout(weapons);
        weapons.setLayout(weaponsLayout);
        weaponsLayout.setHorizontalGroup(
            weaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipos)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        weaponsLayout.setVerticalGroup(
            weaponsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(weaponsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tipos)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        scrollPane.setViewportView(weapons);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nShieldsText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nShields))
                    .addComponent(weaponsText))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nShieldsText)
                    .addComponent(nShields))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(weaponsText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel nShields;
    private javax.swing.JLabel nShieldsText;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JLabel tipos;
    private javax.swing.JPanel weapons;
    private javax.swing.JLabel weaponsText;
    // End of variables declaration//GEN-END:variables
}
