/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import deepspace.WeaponToUI;

/**
 *
 * @author JuanAntonio
 */
public class WeaponView extends javax.swing.JPanel {
    
    private boolean selected=false;
    /**
     * Creates new form WeaponView
     */
    public WeaponView() {
        setOpaque(selected);
        initComponents();
    }
    
    boolean isSelected(){
        return selected;
    }

    void setWeapon(WeaponToUI w){
        Uses.setText(Integer.toString(w.getUses()));
        Power.setText(Float.toString(w.getPower()));
        if(w.getType()==deepspace.WeaponType.LASER)
            Type.setText("LASER");
        if(w.getType()==deepspace.WeaponType.MISSILE)
            Type.setText("MISSILE");
        if(w.getType()==deepspace.WeaponType.PLASMA)
            Type.setText("PLASMA");
        repaint();      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        TypeText = new javax.swing.JLabel();
        UsesText = new javax.swing.JLabel();
        Type = new javax.swing.JLabel();
        Uses = new javax.swing.JLabel();
        PowerText = new javax.swing.JLabel();
        Power = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        name.setText("ARMA");

        TypeText.setText("Tipo:");

        UsesText.setText("Usos:");

        Type.setText("jLabel4");

        Uses.setText("jLabel5");

        PowerText.setText("Potencia:");

        Power.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(TypeText)
                            .addComponent(name))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Type))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PowerText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Power))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UsesText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Uses)))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TypeText)
                    .addComponent(Type))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsesText)
                    .addComponent(Uses))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PowerText)
                    .addComponent(Power))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        selected = !selected;
        setOpaque (selected);
        repaint();
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Power;
    private javax.swing.JLabel PowerText;
    private javax.swing.JLabel Type;
    private javax.swing.JLabel TypeText;
    private javax.swing.JLabel Uses;
    private javax.swing.JLabel UsesText;
    private javax.swing.JLabel name;
    // End of variables declaration//GEN-END:variables
}
